routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('index');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/quick', 'HomeController@quick')->name('quick');
Route::get('/privacy', 'HomeController@privacy')->name('privacy');

Route::get('/admin/stats', 'HomeController@admin')->name('admin.stats');

Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard')->middleware('verified');

Auth::routes(['verify' => true]);

Route::get('/culture/', 'CultureController@index')->name('culture.index');
Route::post('/culture/', 'CultureController@create')->name('culture.create');
Route::get('/culture/{guid}', 'CultureController@show')->name('culture.show');
Route::get('/culture/{guid}/pdf', 'CultureController@pdf')->name('culture.pdf');

Route::get('/heraldry/', 'HeraldryController@index')->name('heraldry.index');
Route::get('/heraldry/charges', 'HeraldryController@charges')->name('heraldry.charges');
Route::post('/heraldry/', 'HeraldryController@create')->name('heraldry.create');
Route::get('/heraldry/{guid}', 'HeraldryController@show')->name('heraldry.show');

Route::get('/region/', 'RegionController@index')->name('region.index');
Route::post('/region/', 'RegionController@create')->name('region.create');
Route::get('/region/{guid}', 'RegionController@show')->name('region.show');

Route::get('/organization/', 'OrganizationController@index')->name('organization.index');
Route::post('/organization/', 'OrganizationController@create')->name('organization.create');
Route::get('/organization/{guid}', 'OrganizationController@show')->name('organization.show');

Route::get('/star_system/', 'StarSystemController@index')->name('star_system.index');
Route::post('/star_system/', 'StarSystemController@create')->name('star_system.create');
Route::get('/star_system/{guid}', 'StarSystemController@show')->name('star_system.show');

Route::post('/users/{user}/set-heraldry/{heraldry}', 'UserController@setPersonalHeraldry')->name('users.set-heraldry');
Route::resource('users', 'UserController');

resources/views/about.blade.php
@extends('layout')

@section('title')
    About Iron Arachne
@endsection

@section('subtitle')
    A quick word about what Iron Arachne is meant to be
@endsection

@section('description')
    About the Iron Arachne website
@endsection

@section('content')
    <h2>About Iron Arachne</h2>
    <p>Iron Arachne&trade; is a project to generate an entire fantasy world completely from scratch in a way that is coherent
        and at least somewhat realistic. Eventually, this will include maps, artwork, calendars, phrasebooks, and
        everything else necessary for a gazetteer about a world.</p>

    <h2>Content Usage</h2>
    <p>Anything generated by this website is yours to use in any capacity you see fit. The heraldry artwork is public
        domain. All generated text and artwork can be used as is, modified, included
        in commercial works, and any other usage without attribution.</p>
    <p>The Iron Arachne&trade; logo is copyright &copy;{{ date('Y') }} Ben Overmyer. All artwork and icons that are not
    specifically called out as public domain is owned in whole or in part, or used under license, by Ben Overmyer.</p>
    <p>I would love to know if you decide to use anything here. Visit my personal site at <a href="https://benovermyer.com">benovermyer.com</a> for contact info.</p>
@endsection

resources/views/dashboard.blade.php
@extends('layout')

@section('title')
    {{ Auth::user()->name }}'s Dashboard
@endsection

@section('subtitle')
    Your personal dashboard
@endsection

@section('content')
    <p>This is your dashboard. Your creations appear here.</p>

    <p><a href="{{ route('users.show', ['user' => Auth::user()]) }}">View your profile</a></p>

    @if(Auth::user()->is_admin)
        <h2><img class="art-icon" src="{{ asset('img/art-icons/admin_gear.png') }}"> Administration</h2>

        <ul>
            <li><a href="{{ route('users.index') }}">List of Users</a></li>
            <li><a href="{{ route('admin.stats') }}">Statistics</a></li>
        </ul>
    @endif

    <h2><img class="art-icon" src="{{ asset('img/art-icons/dashboard_creations.png') }}"> Your Creations</h2>

    <h3>Cultures</h3>

    <ul>
        @foreach ($cultures as $culture)
            <li><a href="{{ route('culture.show', ['guid' => $culture['guid']]) }}">{{ $culture->name }}</a> - {{ $culture->description }}</li>
        @endforeach
    </ul>

    <h3>Regions</h3>

    <ul>
        @foreach ($regions as $region)
            <li><a href="{{ route('region.show', ['guid' => $region['guid']]) }}">{{ $region->name }}</a> - {{ $region->description }}</li>
        @endforeach
    </ul>

    <h3>Heraldry</h3>

    @foreach ($devices as $device)
        <article class="heraldry-list">
            <img src="{{ $device->url }}">
            <p><a href="{{ route('heraldry.show', ['guid' => $device->guid ]) }}">{{ $device->blazon }}</a></p>
        </article>
    @endforeach
@endsection

resources/views/email.blade.php
<!DOCTYPE html>
<html>
<body>
@yield('content')
</body>
</html>

resources/views/index.blade.php
@extends('layout')

@section('title')
    Iron Arachne
@endsection

@section('subtitle')
    Procedural Generation Tools for Tabletop Role-playing Games
@endsection

@section('description')
    Procedural Generation Tools for Tabletop Role-playing Games
@endsection

@section('content')
    <p>This website hosts tools intended to make life easier for players of tabletop RPGs. It's a living website,
        and will continue to receive new tools on a semiregular basis.</p>
    <p>My name is <a href="https://benovermyer.com">Ben Overmyer</a>. I'm the developer behind this site.</p>

    <p>Lastly, if you find this site useful, consider buying me a coffee. The server costs are not cheap, and I fund the site myself.</p>
    <script type="text/javascript" src="https://cdnjs.buymeacoffee.com/1.0.0/button.prod.min.js" data-name="bmc-button" data-slug="benovermyer" data-color="#000000" data-emoji=""  data-font="Cookie" data-text="Buy me a coffee" data-outline-color="#fff" data-font-color="#fff" data-coffee-color="#fd0" ></script>

    @foreach($posts as $post)
        <article class="post">
            <h2><img class="art-icon" src="{{ asset('img/art-icons/blog_post.png') }}"> {{ $post['title'] }}</h2>
            <p class="date">Published {{ date('l F jS, Y', strtotime($post['created'])) }}</p>
            <div>{!! $post['body'] !!}</div>
        </article>
    @endforeach
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html>

<head>
    <title>@yield('title') | Iron Arachne</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="@yield('description')">
    <meta property="og:image" content="@yield('image-metadata', asset('img/ia-logo-small.png'))">
    <link rel="stylesheet" href="{{ asset('css/normalize.css') }}" type="text/css">
    <link rel="stylesheet" href="{{ asset('css/app.css') }}" type="text/css">
    <link rel="apple-touch-icon" sizes="57x57" href="{{ asset('img/apple-icon-57x57.png') }}">
    <link rel="apple-touch-icon" sizes="60x60" href="{{ asset('img/apple-icon-60x60.png') }}">
    <link rel="apple-touch-icon" sizes="72x72" href="{{ asset('img/apple-icon-72x72.png') }}">
    <link rel="apple-touch-icon" sizes="76x76" href="{{ asset('img/apple-icon-76x76.png') }}">
    <link rel="apple-touch-icon" sizes="114x114" href="{{ asset('img/apple-icon-114x114.png') }}">
    <link rel="apple-touch-icon" sizes="120x120" href="{{ asset('img/apple-icon-120x120.png') }}">
    <link rel="apple-touch-icon" sizes="144x144" href="{{ asset('img/apple-icon-144x144.png') }}">
    <link rel="apple-touch-icon" sizes="152x152" href="{{ asset('img/apple-icon-152x152.png') }}">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ asset('img/apple-icon-180x180.png') }}">
    <link rel="icon" type="image/png" sizes="192x192" href="{{ asset('img/android-icon-192x192.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ asset('img/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="96x96" href="{{ asset('img/favicon-96x96.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('img/favicon-16x16.png') }}">
    <link rel="manifest" href="{{ asset('}img/manifest.json') }}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{{ asset('img/ms-icon-144x144.png') }}">
    <meta name="theme-color" content="#ffffff">
    @if (App::environment('production'))
    <script async defer data-website-id="3f86eae1-109d-43b8-b56f-ab8168fae101"
            src="https://umami.benovermyer.com/umami.js"></script>
    @endif
</head>

<body>
<header>
    <img class="logo" src="{{ asset('img/ia-logo-small.png') }}" alt="Iron Arachne logo">
    <div>
        <h1>@yield('title')</h1>
        <p class="subtitle">@yield('subtitle')</p>
    </div>
</header>
<nav class="main" role="navigation" aria-label="main navigation">
    <ul>
        <li><a href="{{ route('index') }}">Main</a></li>
        <li><a href="{{ route('about') }}">About</a></li>
        <li><a href="{{ route('quick') }}">Quick</a></li>
        <li><a href="{{ route('heraldry.index') }}">Heraldry</a></li>
        <li><a href="{{ route('culture.index') }}">Cultures</a></li>
        <li><a href="{{ route('region.index') }}">Regions</a></li>
        <li><a href="{{ route('organization.index') }}">Organizations</a></li>
        <li><a href="{{ route('star_system.index') }}">Star Systems</a></li>

        @if (!Auth::check())
            <li><a href="{{ route('login') }}">Login</a></li>
            <li><a href="{{ route('register') }}">Register</a></li>
        @else
            <li><a href="{{ route('dashboard' ) }}">Dashboard</a></li>
            <li><a href="{{ route('logout') }}"
                   onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                    Logout
                </a></li>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
        @endif
    </ul>
</nav>
<section id="app">
    @yield('content')
</section>
<footer>
    <p class="logo-name">Iron Arachne</p>
    <img class="logo" src="{{ asset('img/ia-logo-small.png') }}" alt="Iron Arachne logo">
    <p><strong>Iron Arachne</strong>&trade; is an ongoing project of <a href="https://benovermyer.com">Ben Overmyer</a>.</p>
    <p>&copy;{{ date('Y') }} Ben Overmyer. All rights reserved.</p>
    <p>You can find source code for this site on <a href="https://gitlab.com/benovermyer/generators-website">GitLab</a>.</p>
    <p><a href="{{ route('privacy') }}">Privacy Policy</a></p>
</footer>
</body>

</html>

resources/views/pdflayout.blade.php
<!DOCTYPE html>
<html>

<head>
    <title>{{ $page->title }}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{{ $page->description }}">
    <link rel="stylesheet" href="{{ asset('css/pdf.css') }}" type="text/css">
</head>

<body>
@yield('content')
</body>

</html>

resources/views/privacy.blade.php
@extends('layout')

@section('title')
    Privacy Policy
@endsection

@section('subtitle')
    This is Iron Arachne's privacy policy.
@endsection

@section('description')
    This is Iron Arachne's privacy policy.
@endsection

@section('content')
    <p>At Iron Arachne, accessible from https://ironarachne.com, one of our main priorities is the privacy of our
        visitors. This Privacy Policy document contains types of information that is collected and recorded by Iron
        Arachne and how we use it.</p>

    <p>If you have additional questions or require more information about our Privacy Policy, do not hesitate to contact
        us.</p>

    <h2>Log Files</h2>

    <p>Iron Arachne follows a standard procedure of using log files. These files log visitors when they visit websites.
        All hosting companies do this and a part of hosting services' analytics. The information collected by log files
        include internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date and time stamp,
        referring/exit pages, and possibly the number of clicks. These are not linked to any information that is
        personally identifiable. The purpose of the information is for analyzing trends, administering the site,
        tracking users' movement on the website, and gathering demographic information.</p>

    <h2>Cookies and Web Beacons</h2>

    <p>Like any other website, Iron Arachne uses 'cookies'. These cookies are used to store information including
        visitors' preferences, and the pages on the website that the visitor accessed or visited. The information is
        used to optimize the users' experience by customizing our web page content based on visitors' browser type
        and/or other information.</p>

    <h2>Privacy Policies</h2>

    <P>You may consult this list to find the Privacy Policy for each of the advertising partners of Iron Arachne. Our
        Privacy Policy was created with the help of the <a href="https://www.privacypolicygenerator.info">Privacy Policy
            Generator</a> and the <a href="https://www.privacypolicyonline.com">Privacy Policy Generator Online</a>.</p>

    <p>Third-party ad servers or ad networks uses technologies like cookies, JavaScript, or Web Beacons that are used in
        their respective advertisements and links that appear on Iron Arachne, which are sent directly to users'
        browser. They automatically receive your IP address when this occurs. These technologies are used to measure the
        effectiveness of their advertising campaigns and/or to personalize the advertising content that you see on
        websites that you visit.</p>

    <p>Note that Iron Arachne has no access to or control over these cookies that are used by third-party
        advertisers.</p>

    <h2>Third Party Privacy Policies</h2>

    <p>Iron Arachne's Privacy Policy does not apply to other advertisers or websites. Thus, we are advising you to
        consult the respective Privacy Policies of these third-party ad servers for more detailed information. It may
        include their practices and instructions about how to opt-out of certain options. You may find a complete list
        of these Privacy Policies and their links here: Privacy Policy Links.</p>

    <p>You can choose to disable cookies through your individual browser options. To know more detailed information
        about cookie management with specific web browsers, it can be found at the browsers' respective websites. What
        Are Cookies?</p>

    <h2>Children's Information</h2>

    <p>Another part of our priority is adding protection for children while using the internet. We encourage parents and
        guardians to observe, participate in, and/or monitor and guide their online activity.</p>

    <p>Iron Arachne does not knowingly collect any Personal Identifiable Information from children under the age of 13.
        If you think that your child provided this kind of information on our website, we strongly encourage you to
        contact us immediately and we will do our best efforts to promptly remove such information from our records.</p>

    <h2>Online Privacy Policy Only</h2>

    <p>This Privacy Policy applies only to our online activities and is valid for visitors to our website with regards
        to the information that they shared and/or collect in Iron Arachne. This policy is not applicable to any
        information collected offline or via channels other than this website.</p>

    <h2>Consent</h2>

    <p>By using our website, you hereby consent to our Privacy Policy and agree to its Terms and Conditions.</p>
@endsection

resources/views/quick.blade.php
@extends('layout')

@section('title')
    Quick Generators
@endsection

@section('subtitle')
    Uncomplicated, quick generators for small things
@endsection

@section('content')
    <p>The following are small generators that you run from this page. These are not saved to your creations.</p>

    <h2><img class="art-icon" src="{{ asset('img/art-icons/alcoholic_drink.png') }}"> Alcoholic Drink Generator</h2>
    <p>This generates a unique alcoholic drink.</p>
    <p>
        <button v-on:click="generateDrink">Generate New Drink</button>
    </p>
    <blockquote>@{{ drinkDescription }}</blockquote>

    <h2><img class="art-icon" src="{{ asset('img/art-icons/chop_shop.png') }}"> Cyberpunk Chop Shop Generator</h2>
    <p>Part of the <a href="https://reddit.com/r/rpg_generators">r/rpg_generators</a> subreddit <a
            href="https://www.reddit.com/r/rpg_generators/comments/ftnsx4/cyberpunk_for_april_rpg_generators_challenge/">Cyberpunk
            Challenge</a> for April 2020. This generates a cyberpunk chop shop.</p>
    <p>
        <button v-on:click="generateChopShop">Generate New Chop Shop</button>
    </p>
    <blockquote>@{{ chopShopDescription }}</blockquote>

    <h2><img class="art-icon" src="{{ asset('img/art-icons/language.png') }}"> Language Generator</h2>
    <p>This generates a description of a fantasy language for you.</p>
    <p>
        <button v-on:click="generateLanguage">Generate New Language</button>
    </p>
    <blockquote>@{{ languageDescription }}</blockquote>

    <h2><img class="art-icon" src="{{ asset('img/art-icons/organization.png') }}"> Organization Generator</h2>
    <p>This generates a fantasy organization.</p>
    <p>
        <button v-on:click="generateOrganization">Generate New Organization</button>
    </p>
    <blockquote class="organization"><img v-bind:src="organizationHeraldry">
        <p>@{{ organizationDescription }}</p></blockquote>

    <h2><img class="art-icon" src="{{ asset('img/art-icons/town_medium.png') }}"> Town Generator</h2>
    <p>Need a quick town? Click here.</p>
    <p>
        <button v-on:click="generateTown">Generate New Town</button>
    </p>
    <blockquote>@{{ townDescription }}</blockquote>

    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.min.js"></script>
    <script type="text/javascript">
        function getRandomInt(max) {
            return Math.floor(Math.random() * Math.floor(max))
        }

        function getRandomItem(items) {
            var item = items[Math.floor(Math.random() * items.length)]

            return item
        }

        function getCSFront() {
            choices = [
                "Outside, a large neon sign proclaims the name of the shop, the brightness of the writing diffused by thick smog.",
                "A vagrant slumps against the wall next to the door of the shop. He clutches a brown paper bag in his good hand, the other hand a wreckage of cybernetics that no longer appear functional.",
                "The shop's dark exterior walls are offset by neon lights bordering the doorway, giving it the appearance of a portal into another world."
            ]

            return getRandomItem(choices)
        }

        function getCSEntry() {
            choices = [
                "As you go inside, you notice a handful of locals watch you with hard eyes, then turn away.",
                "You open the door to the shop, and a soft chime announces your entry.",
                "Entry to the shop sets off a soft chime to alert the staff."
            ]

            return getRandomItem(choices)
        }

        function getCSProductDisplays() {
            choices = [
                "The shop's wares are displayed on large screens placed throughout the front room.",
                "A handful of model cybernetics lay strewn haphazardly on shelves in the front room. Beside the shelves are a couple old displays, their screens flickering and dull.",
                "Each of the shop's offerings is shown on a screen that takes up an entire wall.",
                "A couple attendants in bright uniforms greet customers and answer questions about the shop's offerings."
            ]

            return getRandomItem(choices)
        }

        function getCSCustomers() {
            choices = [
                "A few customers silently shuffle through the displays or wait in the small lobby for patients.",
                "One or two people wait in the back for their turn under the knife.",
                "Several people are standing in front of the display screens, flipping curiously through the options. The chairs and benches in the patient lobby are all full."
            ]

            return getRandomItem(choices)
        }

        function getCSBack() {
            choices = [
                "The operating room is bright and clean. Two technicians in immaculate uniforms assist the cyberdoc.",
                "In the back, a single operating table sits in the center of the room surrounded by harsh white lights.",
                "In the back, the sole cyberdoc of the shop stands over an operating table. Tools of various types and sizes sit on shelves nearby.",
            ]

            return getRandomItem(choices)
        }

        var app = new Vue({
            el: '#app',
            data: {
                chopShopDescription: '',
                drinkDescription: '',
                languageDescription: '',
                languageName: '',
                organizationDescription: '',
                organizationHeraldry: '',
                townDescription: ''
            },
            methods: {
                generateChopShop: function (event) {
                    description = getCSFront() + " " + getCSEntry() + " " + getCSProductDisplays() + " " + getCSCustomers() + " " + getCSBack()
                    this.chopShopDescription = description
                },
                generateDrink: function (event) {
                    this.drinkDescription = 'Generating...'

                    url = '{{ route('api.alcoholic_drink.random') }}'

                    fetch(url)
                        .then(response => response.json())
                        .then(response => {
                            this.drinkDescription = response.alcoholic_drink.description
                        })
                        .catch(error => console.error(error));
                },
                generateLanguage: function (event) {
                    this.languageDescription = 'Generating...'

                    url = '{{ route('api.language.random') }}'

                    fetch(url)
                        .then(response => response.json())
                        .then(response => {
                            this.languageDescription = response.language.description
                        })
                        .catch(error => console.error(error));
                },
                generateOrganization: function (event) {
                    this.organizationDescription = 'Generating...'
                    this.organizationHeraldry = ''

                    url = '{{ route('api.organization.random') }}'

                    fetch(url)
                        .then(response => response.json())
                        .then(response => {
                            this.organizationDescription = response.organization.description
                            this.organizationHeraldry = response.organization.heraldry.image_url
                        })
                        .catch(error => console.error(error));
                },
                generateTown: function (event) {
                    this.townDescription = 'Generating...'

                    url = '{{ route('api.town.random') }}'

                    fetch(url)
                        .then(response => response.json())
                        .then(response => {
                            this.townDescription = response.town.description
                        })
                        .catch(error => console.error(error));
                }
            }
        })

        app.generateChopShop()
        app.generateDrink()
        app.generateLanguage()
        app.generateOrganization()
        app.generateTown()
    </script>
@endsection