routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('index');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/quick', 'HomeController@quick')->name('quick');
Route::get('/privacy', 'HomeController@privacy')->name('privacy');

Route::get('/admin/stats', 'HomeController@admin')->name('admin.stats');

Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard')->middleware('verified');

Auth::routes(['verify' => true]);

Route::get('/culture/', 'CultureController@index')->name('culture.index');
Route::post('/culture/', 'CultureController@create')->name('culture.create');
Route::get('/culture/{guid}', 'CultureController@show')->name('culture.show');
Route::get('/culture/{guid}/pdf', 'CultureController@pdf')->name('culture.pdf');

Route::get('/heraldry/', 'HeraldryController@index')->name('heraldry.index');
Route::get('/heraldry/charges', 'HeraldryController@charges')->name('heraldry.charges');
Route::post('/heraldry/', 'HeraldryController@create')->name('heraldry.create');
Route::get('/heraldry/{guid}', 'HeraldryController@show')->name('heraldry.show');

Route::get('/region/', 'RegionController@index')->name('region.index');
Route::post('/region/', 'RegionController@create')->name('region.create');
Route::get('/region/{guid}', 'RegionController@show')->name('region.show');

Route::get('/organization/', 'OrganizationController@index')->name('organization.index');
Route::post('/organization/', 'OrganizationController@create')->name('organization.create');
Route::get('/organization/{guid}', 'OrganizationController@show')->name('organization.show');

Route::get('/star_system/', 'StarSystemController@index')->name('star_system.index');
Route::post('/star_system/', 'StarSystemController@create')->name('star_system.create');
Route::get('/star_system/{guid}', 'StarSystemController@show')->name('star_system.show');

Route::post('/users/{user}/set-heraldry/{heraldry}', 'UserController@setPersonalHeraldry')->name('users.set-heraldry');
Route::resource('users', 'UserController');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function heraldry()
    {
        return $this->hasOne('App\Heraldry', 'claimant_id');
    }

    public function cultures()
    {
        return $this->hasMany('App\SavedCulture');
    }

    public function heraldries()
    {
        return $this->hasMany('App\Heraldry');
    }

    public function organizations()
    {
        return $this->hasMany('App\SavedOrganization');
    }

    public function regions()
    {
        return $this->hasMany('App\SavedRegion');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Heraldry;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        Gate::authorize('list-users');

        $users = User::paginate(15);

        return view('user.index', ['users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        Gate::authorize('create-user');

        return view('user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Gate::authorize('create-user');

        $user = User::create([
            'name' => $request->input('name'),
            'email' => $request->input('email'),
            'password' => Hash::make($request->input('password')),
        ]);

        return redirect()->route('users.show', ['user' => $user]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('user.show', ['user' => $user]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        Gate::authorize('edit-user', $user);

        return view('user.edit', ['user' => $user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        Gate::authorize('edit-user', $user);

        $user->name = $request->input('name');
        $user->email = $request->input('email');
        $user->save();

        return redirect()->route('users.show', ['user' => $user]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        Gate::authorize('delete-user', $user);

        $user->delete();

        return redirect()->route('users.index');
    }

    public function setPersonalHeraldry(User $user, Heraldry $heraldry) {
        Gate::authorize('set-heraldry-for-user', $user);

        if (!empty($user->heraldry)) {
            $oldHeraldry = $user->heraldry;
            $oldHeraldry->owner()->dissociate();
            $oldHeraldry->save();
            Cache::forever('heraldry-' . $oldHeraldry->guid, $oldHeraldry);
        }

        $heraldry->owner()->associate($user);
        $heraldry->save();
        Cache::forever('heraldry-' . $heraldry->guid, $heraldry);

        $user->heraldry()->save($heraldry);

        return redirect()->route('users.show', ['user' => $user]);
    }
}

resources/views/user/create.blade.php
@extends('layout')

@section('title')
    Create User
@endsection

@section('description')
    Create a new user
@endsection

@section('content')
    <h2>Create User</h2>

    @if ($errors->any())
        @foreach($errors->all() as $error)
            <p>{{ $error }}</p>
        @endforeach
    @endif

    <form method="POST" action="{{ route('users.store') }}">
        @csrf
        <div class="input-group">
            <label for="name">Display Name</label>
            <input type="text" name="name">
        </div>

        <div class="input-group">
            <label for="email">Email Address</label>
            <input type="email" name="email">
        </div>

        <div class="input-group">
            <label for="password">Password</label>
            <input type="password" name="password">
        </div>

        <div class="input-group">
            <label for="password_confirmation">Confirm Password</label>
            <input type="password" name="password_confirmation">
        </div>

        <input type="submit" value="Create">
    </form>
@endsection

resources/views/user/edit.blade.php
@extends('layout')

@section('title')
    Edit User {{ $user->name }}
@endsection

@section('description')
    Edit {{ $user->name }}
@endsection

@section('content')
    <h2>Editing User</h2>

    @if ($errors->any())
        @foreach($errors->all() as $error)
            <p>{{ $error }}</p>
        @endforeach
    @endif

    <form method="POST" action="{{ route('users.update', ['user' => $user]) }}">
        @method('PUT')
        @csrf
        <div class="input-group">
            <label for="name">Display Name</label>
            <input type="text" name="name" value="{{ $user->name }}">
        </div>

        <div class="input-group">
            <label for="email">Email Address</label>
            <input type="email" name="email" value="{{ $user->email }}">
        </div>

        <input type="submit" value="Save Changes">
    </form>

    <p><a href="{{ route('password.request') }}">Need to change your password?</a></p>
@endsection

resources/views/user/index.blade.php
@extends('layout')

@section('title')
    Users
@endsection

@section('description')
    All users
@endsection

@section('content')
    <h2>Users</h2>

    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Heraldry</th>
                <th>Regions</th>
                <th>Cultures</th>
                <th>Created</th>
            </tr>
        </thead>
        <tbody>
        @foreach($users as $user)
            <tr>
                <td><a href="{{ route('users.show', ['user' => $user]) }}">{{ $user->name }}</a></td>
                <td>{{ $user->email }}</td>
                <td>{{ $user->heraldries->count() }}</td>
                <td>{{ $user->regions->count() }}</td>
                <td>{{ $user->cultures->count() }}</td>
                <td>{{ date('Y-m-d', strtotime($user->created_at)) }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>

    {{ $users->links() }}
@endsection

resources/views/user/show.blade.php
@extends('layout')

@section('title')
    {{ $user->name }}'s Profile
@endsection

@section('description')
    {{ $user->name }}'s User Profile
@endsection

@section('content')
    <h2>{{ $user->name }}'s Profile</h2>

    @if ($errors->any())
        @foreach($errors->all() as $error)
            <p>{{ $error }}</p>
        @endforeach
    @endif

    @if(!empty(Auth::user()->heraldry->url))
        <img src="{{ Auth::user()->heraldry->url }}">
    @endif

    @if(Auth::user()->is_admin)
        <p>Email Address: {{ $user->email }}</p>
        <p>Created {{ date('F j, Y, g:i a', strtotime($user->created_at)) }}</p>
    @endif

    @if(Auth::user()->id == $user->id)
        <p>This is you!</p>
        <p>Your email: {{ $user->email }}</p>
        <a href="{{ route('users.edit', ['user' => $user]) }}" class="button">Edit</a>
    @endif
@endsection